//
// Generated file, do not edit! Created by opp_msgc 4.1 from networklayer/RPL/DAOACKMessage.msg.
//

#ifndef _DAOACKMESSAGE_M_H_
#define _DAOACKMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>networklayer/RPL/DAOACKMessage.msg</tt> by opp_msgc.
 * <pre>
 * packet DAOACKMessage {
 *     int someField;
 *     string anotherField;
 *     double arrayField1[];
 *     double arrayField2[10];
 * }
 * </pre>
 */
class DAOACKMessage : public ::cPacket
{
  protected:
    int someField_var;
    opp_string anotherField_var;
    double *arrayField1_var; // array ptr
    unsigned int arrayField1_arraysize;
    double arrayField2_var[10];

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DAOACKMessage&);

  public:
    DAOACKMessage(const char *name=NULL, int kind=0);
    DAOACKMessage(const DAOACKMessage& other);
    virtual ~DAOACKMessage();
    DAOACKMessage& operator=(const DAOACKMessage& other);
    virtual DAOACKMessage *dup() const {return new DAOACKMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getSomeField() const;
    virtual void setSomeField(int someField_var);
    virtual const char * getAnotherField() const;
    virtual void setAnotherField(const char * anotherField_var);
    virtual void setArrayField1ArraySize(unsigned int size);
    virtual unsigned int getArrayField1ArraySize() const;
    virtual double getArrayField1(unsigned int k) const;
    virtual void setArrayField1(unsigned int k, double arrayField1_var);
    virtual unsigned int getArrayField2ArraySize() const;
    virtual double getArrayField2(unsigned int k) const;
    virtual void setArrayField2(unsigned int k, double arrayField2_var);
};

inline void doPacking(cCommBuffer *b, DAOACKMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, DAOACKMessage& obj) {obj.parsimUnpack(b);}


#endif // _DAOACKMESSAGE_M_H_
